# Performance of L2_HR_LAKESP products with filters

* [Setup](#Setup)
* [Run stats AREA](#Run-stats-AREA)
* [Run stats WSE](#Run-stats-WSE)

In [1]:
input_dir = "/work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/input"
output_dir = "/work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output"

## Setup

In [2]:
import sys
from datetime import date
import os
import pandas as pd
# Update PYTHONPATH
sys.path.append("/work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/")

import src.stats_lakesp as my_perfos

no display found. Using non-interactive Agg backend

In [3]:
today = date.today()
cur_date = today.strftime("%Y%m%d")
cur_date

'20260209'

## Run stats AREA

### 1°) Retrieve swot_lakesp_diff data

In [4]:
df_diff = pd.read_csv(os.path.join(input_dir, "diff_area.csv"), sep=";")                         # dataset without filtering xtrk_dist
# df_diff = pd.read_csv(os.path.join(input_dir, "diff_area_with_xtrack_filtering.csv"), sep=";") # dataset with filtering xtrk_dist
df_diff.head()

,_fuid,_time,time_truth1,time_truth2,cycle_number,pass_number,wse,wse_u,wse_levelled,area_total,...,partial_f,ice_f,quality_f,xovr_cal_q,xovr_cal_c,valid_flag,qual_f_b,crid,lake_id,p_ref_area
0,ExtractEO_TP:1810010652,2023-04-01 20:02:25,2023-04-03,NaN,477,27,NaN,NaN,NaN,-0.334785,...,0,0,1,0,-0.683618,1,10,PGD0,1810010652,0.1521
1,ExtractEO_TP:1810010652,2023-04-15 17:51:16,2023-04-18,NaN,491,27,NaN,NaN,NaN,-0.533693,...,0,0,0,0,0.906273,1,0,PGD0,1810010652,0.1521
2,ExtractEO_TP:1810010652,2023-04-19 17:13:48,2023-04-18,NaN,495,27,NaN,NaN,NaN,-0.520934,...,0,0,1,0,1.347246,1,11,PGD0,1810010652,0.1521
3,ExtractEO_TP:1810010652,2023-04-28 15:49:29,2023-04-28,NaN,504,27,NaN,NaN,NaN,-0.240432,...,0,0,0,0,2.248633,1,0,PGD0,1810010652,0.1521
4,ExtractEO_TP:1810010652,2023-05-02 15:12:00,2023-05-03,NaN,508,27,NaN,NaN,NaN,-0.519618,...,0,0,0,0,1.875022,1,0,PGD0,1810010652,0.1521

In [5]:
len(df_diff)

246169

In [6]:
case='area'

In [7]:
out_dir = os.path.join(output_dir, "lakes_perfos_{}_{}".format(case, cur_date))
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
out_dir

'/work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260209'

### 2°) Compute stats with filters, for Pleiades + RCM

In [8]:
# Filtrer les lignes où _fuid commence par 'SLUM_TP:' ou 'RCM_TP:'
df_filtered = df_diff[df_diff['_fuid'].str.startswith(('SLUM_TP:', 'RCM_TP:'))]
len(df_filtered)

40551

#### 2.0°) No filtering

In [9]:
suffix_dir = "M_no_filtering"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_filtered, which_stats="area_total", which_perfos="goal")

> area_total / goal / global 1s error slices (1): 42.865 %
> area_total / goal / global 1s error slices (2): 32.176 %
> area_total / goal / global 1s error slices (3): 14.516 %
Number of PLD lakes: 1633
Number of matchups: 40551
Figure saved: 1_nb_diff_per_size.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260209/M_no_filtering
Figure saved: 2_1s_error_per_size.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260209/M_no_filtering
Figure saved: 3_error_per_xtrack.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260209/M_no_filtering
Figure saved: 4_med_error_per_xtrack.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260209/M_no_filtering
Figure saved: 5_nb_lakes_per_size.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260209/M_no_filtering

#### 2.1°) partial_f = 0

In [10]:
df_subset = df_filtered[df_filtered["partial_f"] == 0]

In [11]:
suffix_dir = "M_partial_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0/goal directory doesn't exist => create it
Number of PLD lakes: 1611
Number of matchups: 39462
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 42.219 %
> reference_surface_area / goal / global 1s error slices (2): 30.857 %
> reference_surface_area / goal / global 1s error slices (3): 12.814 %

#### 2.2°) partial_f = 0 + ice_f = 0

In [12]:
df_subset = df_filtered[(df_filtered["partial_f"] == 0) & (df_filtered["ice_f"] == 0)]

In [13]:
suffix_dir = "M_partial_f_eq0_ice_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0_ice_f_eq0/goal directory doesn't exist => create it
Number of PLD lakes: 1609
Number of matchups: 39394
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0_ice_f_eq0/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 42.219 %
> reference_surface_area / goal / global 1s error slices (2): 30.898 %
> reference_surface_area / goal / global 1s error slices (3): 12.381 %

#### 2.3°) partial_f = 0 + ice_f = 0 + quality_f=0,1,2

In [14]:
df_subset = df_filtered[
    (df_filtered["partial_f"] == 0) &
    (df_filtered["ice_f"] == 0) &
    (df_filtered["quality_f"].isin([0, 1, 2]))
]

In [15]:
suffix_dir = "M_partial_f_eq0_ice_f_eq0_quality_f_eq0_1_2"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0_ice_f_eq0_quality_f_eq0_1_2/goal directory doesn't exist => create it
Number of PLD lakes: 1601
Number of matchups: 37020
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0_ice_f_eq0_quality_f_eq0_1_2/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 41.357 %
> reference_surface_area / goal / global 1s error slices (2): 29.809 %
> reference_surface_area / goal / global 1s error slices (3): 12.041 %

#### 2.4°) partial_f = 0 + ice_f = 0 + quality_f=0,1

In [16]:
df_subset = df_filtered[
    (df_filtered["partial_f"] == 0) &
    (df_filtered["ice_f"] == 0) &
    (df_filtered["quality_f"].isin([0, 1]))
]

In [17]:
suffix_dir = "M_partial_f_eq0_ice_f_eq0_quality_f_eq0_1"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0_ice_f_eq0_quality_f_eq0_1/goal directory doesn't exist => create it
Number of PLD lakes: 1591
Number of matchups: 36145
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0_ice_f_eq0_quality_f_eq0_1/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 40.960 %
> reference_surface_area / goal / global 1s error slices (2): 29.812 %
> reference_surface_area / goal / global 1s error slices (3): 12.186 %

#### 2.5°) partial_f = 0 + ice_f = 0 + quality_f=0

In [18]:
df_subset = df_filtered[(df_filtered["partial_f"] == 0) & (df_filtered["ice_f"] == 0) & (df_filtered["quality_f"] == 0)]

In [19]:
suffix_dir = "M_partial_f_eq0_ice_f_eq0_quality_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0_ice_f_eq0_quality_f_eq0/goal directory doesn't exist => create it
Number of PLD lakes: 668
Number of matchups: 11182
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/M_partial_f_eq0_ice_f_eq0_quality_f_eq0/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 19.030 %
> reference_surface_area / goal / global 1s error slices (2): 14.425 %
> reference_surface_area / goal / global 1s error slices (3): 9.128 %

### 3°) Compute stats with filters, for ExtractEO

In [20]:
# Filtrer les lignes où _fuid commence par 'ExtractEO_TP:'
df_filtered = df_diff[df_diff['_fuid'].str.startswith(('ExtractEO_TP:'))]
len(df_filtered)

205618

#### 3.0°) No filtering

In [21]:
suffix_dir = "EO_no_filtering"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_filtered, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_no_filtering/goal directory doesn't exist => create it
Number of PLD lakes: 10655
Number of matchups: 205618
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_no_filtering/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 84.189 %
> reference_surface_area / goal / global 1s error slices (2): 44.996 %
> reference_surface_area / goal / global 1s error slices (3): 23.554 %

#### 3.1°) partial_f = 0

In [22]:
df_subset = df_filtered[df_filtered["partial_f"] == 0]

In [23]:
suffix_dir = "EO_partial_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0/goal directory doesn't exist => create it
Number of PLD lakes: 10411
Number of matchups: 198088
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 82.699 %
> reference_surface_area / goal / global 1s error slices (2): 42.853 %
> reference_surface_area / goal / global 1s error slices (3): 19.730 %

#### 3.2°) partial_f = 0 + ice_f = 0

In [24]:
df_subset = df_filtered[(df_filtered["partial_f"] == 0) & (df_filtered["ice_f"] == 0)]

In [25]:
suffix_dir = "EO_partial_f_eq0_ice_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0_ice_f_eq0/goal directory doesn't exist => create it
Number of PLD lakes: 10004
Number of matchups: 175633
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0_ice_f_eq0/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 79.856 %
> reference_surface_area / goal / global 1s error slices (2): 43.097 %
> reference_surface_area / goal / global 1s error slices (3): 21.238 %

#### 3.3°) partial_f = 0 + ice_f = 0 + quality_f=0,1,2

In [26]:
df_subset = df_filtered[
    (df_filtered["partial_f"] == 0) &
    (df_filtered["ice_f"] == 0) &
    (df_filtered["quality_f"].isin([0, 1, 2]))
]

In [27]:
suffix_dir = "EO_partial_f_eq0_ice_f_eq0_quality_f_eq0_1_2"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0_ice_f_eq0_quality_f_eq0_1_2/goal directory doesn't exist => create it
Number of PLD lakes: 9974
Number of matchups: 170094
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0_ice_f_eq0_quality_f_eq0_1_2/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 79.615 %
> reference_surface_area / goal / global 1s error slices (2): 43.601 %
> reference_surface_area / goal / global 1s error slices (3): 21.473 %

#### 3.4°) partial_f = 0 + ice_f = 0 + quality_f=0,1

In [28]:
df_subset = df_filtered[
    (df_filtered["partial_f"] == 0) &
    (df_filtered["ice_f"] == 0) &
    (df_filtered["quality_f"].isin([0, 1]))
]

In [29]:
suffix_dir = "EO_partial_f_eq0_ice_f_eq0_quality_f_eq0_1"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0_ice_f_eq0_quality_f_eq0_1/goal directory doesn't exist => create it
Number of PLD lakes: 9871
Number of matchups: 163280
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0_ice_f_eq0_quality_f_eq0_1/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 78.198 %
> reference_surface_area / goal / global 1s error slices (2): 43.503 %
> reference_surface_area / goal / global 1s error slices (3): 21.622 %

#### 3.5°) partial_f = 0 + ice_f = 0 + quality_f=0

In [30]:
df_subset = df_filtered[(df_filtered["partial_f"] == 0) & (df_filtered["ice_f"] == 0) & (df_filtered["quality_f"] == 0)]

In [31]:
suffix_dir = "EO_partial_f_eq0_ice_f_eq0_quality_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="area_total", which_perfos="goal")

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0_ice_f_eq0_quality_f_eq0/goal directory doesn't exist => create it
Number of PLD lakes: 3269
Number of matchups: 36621
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_area_20260205/EO_partial_f_eq0_ice_f_eq0_quality_f_eq0/goal/fig_surface-area_scene-all_swath-nominal_4
> reference_surface_area / goal / global 1s error slices (1): 30.233 %
> reference_surface_area / goal / global 1s error slices (2): 23.782 %
> reference_surface_area / goal / global 1s error slices (3): 16.330 %

## Run stats WSE

### 1°) Retrieve swot_lakesp_diff data

In [10]:
# df_diff = pd.read_csv(os.path.join(input_dir, "diff_wse.csv"), sep=";")
df_diff = pd.read_csv(os.path.join(input_dir, "1_diff_with_prefarea.csv"), sep=";")
df_diff.head()

,_fuid,_time,time_truth1,time_truth2,geometry,cycle_number,pass_number,wse,wse_u,wse_levelled,...,partial_f,ice_f,quality_f,xovr_cal_q,xovr_cal_c,valid_flag,qual_f_b,crid,lake_id,p_ref_area
0,bafu:2140010723:1,2023-09-09 08:46:14,2023-09-09 08:00:00,2023-09-09 09:00:00,NaN,3,236,-0.031158,0.05,True,...,1,0.0,2,0,-0.012665,1,622592,PGD0,2140010723,211.47064
1,bafu:2140010723:1,2023-09-11 22:06:04,2023-09-11 22:00:00,2023-09-11 23:00:00,NaN,3,307,-6.653370,0.05,True,...,1,0.0,3,0,-0.008706,1,67207232,PGD0,2140010723,211.47064
2,bafu:2140010723:1,2025-05-06 10:33:29,2025-05-06 10:00:00,2025-05-06 11:00:00,NaN,32,236,-0.025800,0.05,True,...,1,0.0,2,0,-0.290911,1,622592,PID0,2140010723,211.47064
3,bafu:2140010723:1,2025-05-08 23:53:18,2025-05-08 23:00:00,2025-05-09 00:00:00,NaN,32,307,-2.257922,0.05,True,...,1,0.0,1,0,0.224469,1,67,PID0,2140010723,211.47064
4,bafu:2140010723:1,2025-05-27 07:18:35,2025-05-27 07:00:00,2025-05-27 08:00:00,NaN,33,236,-0.043470,0.05,True,...,1,0.0,2,0,0.241376,1,622592,PID0,2140010723,211.47064

In [11]:
len(df_diff)

22960

In [12]:
# df_diff["source_name"] = df_diff["_fuid"].str.split(":").str[0]
# df_diff["source_name"].unique()

In [13]:
case='wse'

In [14]:
out_dir = os.path.join(output_dir, "lakes_perfos_{}_{}".format(case, cur_date))
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
out_dir

'/work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260209'

### 2°) Compute stats with filters, for sources: 
### bafu, ceara_wse, cehq, curuai, eccc_gnss, hydroquebec, lake_us, locss_pyrenees, nve, oecs_lake, sertit, sget, smhi, spence, tibet, udes, usgs

#### 2.0°) No filtering

In [15]:
suffix_dir = "no_filtering"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_diff, which_stats="wse", which_perfos="req", flag_levelled=True)

Keep 22960 / 22960 lines after filter over filter_nivelled
> wse / req / global 1s error slices (1): 0.147 m
> wse / req / global 1s error slices (2): 0.220 m
> wse / req / global 1s error slices (3): 0.000 m
Number of PLD lakes: 673
Number of matchups: 22960
Figure saved: 1_nb_diff_per_size.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260209/no_filtering
Figure saved: 2_1s_error_per_size.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260209/no_filtering
Figure saved: 3_error_per_xtrack.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260209/no_filtering
Figure saved: 4_med_error_per_xtrack.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260209/no_filtering
Figure saved: 5_nb_lakes_per_size.png in /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260209/no_filtering

#### 2.1°) ice_f = 0,1

In [10]:
df_subset = df_diff[df_diff["ice_f"].isin([0, 1])]

In [11]:
suffix_dir = "ice_f_eq0_1"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="wse", which_perfos="req", flag_levelled=True)

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_1/req directory doesn't exist => create it
Keep 20364 / 20364 lines after filter over filter_nivelled
Number of PLD lakes: 656
Number of matchups: 20364
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_1/req/fig_wse_scene-all_swath-nominal_4
> reference_wse / req / global 1s error slices (1): 0.144 m
> reference_wse / req / global 1s error slices (2): 0.176 m
> reference_wse / req / global 1s error slices (3): 0.000 m

#### 2.2°) ice_f = 0

In [40]:
df_subset = df_diff[df_diff["ice_f"] == 0]

In [41]:
suffix_dir = "ice_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="wse", which_perfos="req", flag_levelled=True)

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0/req directory doesn't exist => create it
Keep 16667 / 16667 lines after filter over filter_nivelled
Number of PLD lakes: 656
Number of matchups: 16667
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0/req/fig_wse_scene-all_swath-nominal_4
> reference_wse / req / global 1s error slices (1): 0.141 m
> reference_wse / req / global 1s error slices (2): 0.139 m
> reference_wse / req / global 1s error slices (3): 0.000 m

#### 2.3°) ice_f = 0 + partial_f = 0

In [42]:
df_subset = df_diff[(df_diff["ice_f"] == 0) & (df_diff["partial_f"] == 0)]

In [43]:
suffix_dir = "ice_f_eq0_partial_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="wse", which_perfos="req", flag_levelled=True)

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_partial_f_eq0/req directory doesn't exist => create it
Keep 9663 / 9663 lines after filter over filter_nivelled
Number of PLD lakes: 564
Number of matchups: 9663
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_partial_f_eq0/req/fig_wse_scene-all_swath-nominal_4
> reference_wse / req / global 1s error slices (1): 0.133 m
> reference_wse / req / global 1s error slices (2): 0.109 m
> reference_wse / req / global 1s error slices (3): 0.000 m

#### 2.4°) ice_f = 0 + partial_f = 0 + quality_f=0,1,2

In [44]:
df_subset = df_diff[
    (df_diff["ice_f"] == 0) &
    (df_diff["partial_f"] == 0) &
    (df_diff["quality_f"].isin([0, 1, 2]))
]

In [45]:
suffix_dir = "ice_f_eq0_partial_f_eq0_quality_f_eq0_1_2"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="wse", which_perfos="req", flag_levelled=True)

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_partial_f_eq0_quality_f_eq0_1_2/req directory doesn't exist => create it
Keep 9319 / 9319 lines after filter over filter_nivelled
Number of PLD lakes: 562
Number of matchups: 9319
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_partial_f_eq0_quality_f_eq0_1_2/req/fig_wse_scene-all_swath-nominal_4
> reference_wse / req / global 1s error slices (1): 0.129 m
> reference_wse / req / global 1s error slices (2): 0.106 m
> reference_wse / req / global 1s error slices (3): 0.000 m

/work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/src/lib_relative_errors.py:700: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig=plt.figure(figsize=(10, 4))

#### 2.5°) ice_f = 0 + partial_f = 0 + quality_f=0,1

In [46]:
df_subset = df_diff[
    (df_diff["ice_f"] == 0) &
    (df_diff["partial_f"] == 0) &
    (df_diff["quality_f"].isin([0, 1]))
]

In [47]:
suffix_dir = "ice_f_eq0_partial_f_eq0_quality_f_eq0_1"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="wse", which_perfos="req", flag_levelled=True)

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_partial_f_eq0_quality_f_eq0_1/req directory doesn't exist => create it
Keep 8665 / 8665 lines after filter over filter_nivelled
Number of PLD lakes: 558
Number of matchups: 8665
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_partial_f_eq0_quality_f_eq0_1/req/fig_wse_scene-all_swath-nominal_4
> reference_wse / req / global 1s error slices (1): 0.129 m
> reference_wse / req / global 1s error slices (2): 0.106 m
> reference_wse / req / global 1s error slices (3): 0.000 m

/work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/src/lib_relative_errors.py:597: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig = plt.figure(figsize=(10, 4))

#### 2.6°) ice_f = 0 + partial_f = 0 + quality_f=0

In [48]:
df_subset = df_diff[
    (df_diff["ice_f"] == 0) &
    (df_diff["partial_f"] == 0) &
    (df_diff["quality_f"] == 0)
]

In [49]:
suffix_dir = "ice_f_eq0_partial_f_eq0_quality_f_eq0"
my_perfos.plot_stats(os.path.join(out_dir, suffix_dir), df_subset, which_stats="wse", which_perfos="req", flag_levelled=True)

[WARNING] /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_partial_f_eq0_quality_f_eq0/req directory doesn't exist => create it
Keep 5208 / 5208 lines after filter over filter_nivelled
Number of PLD lakes: 455
Number of matchups: 5208
Number of lakes figure is saved to the disk! Here: /work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/examples/output/lakes_perfos_wse_20260205/ice_f_eq0_partial_f_eq0_quality_f_eq0/req/fig_wse_scene-all_swath-nominal_4
> reference_wse / req / global 1s error slices (1): 0.114 m
> reference_wse / req / global 1s error slices (2): 0.091 m
> reference_wse / req / global 1s error slices (3): 0.000 m

/work/EXPERT_CENTER/mwec/workspace/HR/labatl/scripts/swot-hydrology-toolbox/performances/src/lib_relative_errors.py:750: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig = plt.figure(figsize=(10, 4))